# Generated by Django 5.0.4 on 2024-05-07 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserTexList',
            fields=[
                ('username', models.CharField(max_length=120, primary_key=True, serialize=False)),
                ('tex_list', models.TextField(null=True)),
            ],
        ),
    ]
