# Generated by Django 5.0.4 on 2024-05-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_book_olimp_problem_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='num',
            field=models.CharField(default='', max_length=5),
        ),
    ]
