# Generated by Django 5.0.4 on 2024-05-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0003_alter_problem_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='problem',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
